name: Delete branch
description: Delete a single branch from repository
author: dawidd6
branding:
  icon: git-branch
  color: red
inputs:
  github_token:
    description: Github token
    required: true
  branch:
    description: Branch name to delete
    required: true
  be_kind:
    description: Be kind and do not scream if an exception occurs
    required: false
    default: false
runs:
  using: docker
  image: Dockerfile