name: Delete multiple branches
description: Delete multiple branches from repository
author: dawidd6
branding:
  icon: git-branch
  color: red
inputs:
  github_token:
    description: Github token
    required: true
  branches:
    description: Branches to delete (comma separated)
    required: false
  numbers:
    description: PR numbers whose head branches should be deleted (comma separated)
    required: false
  prefix:
    description: Additional prefix to append to every branch name
    required: false
  suffix:
    description: Additional suffix to append to every branch name
    required: false
runs:
  using: docker
  image: Dockerfile
