name: Delete multiple branches
description: Delete multiple branches from repository
author: dawidd6
branding:
  icon: git-branch
  color: red
inputs:
  github_token:
    description: GitHub token
    required: false
    default: ${{github.token}}
  owner:
    description: Owner of the repository. Will be deducted from github_token if it is not provided
    required: false
  repository:
    description: The repository containing the branch(es) to be deleted. Will be deducted from github_token if it is not provided
    required: false
  branches:
    description: Branches to delete (comma separated)
    required: false
  numbers:
    description: PR numbers whose head branches should be deleted (comma separated)
    required: false
  prefix:
    description: Additional prefix to append to every branch name
    required: false
  suffix:
    description: Additional suffix to append to every branch name
    required: false
runs:
  using: node12
  main: main.js
