name: Test action

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create branches
        run: |
          git checkout -b test1
          git push origin test1
          git checkout -b test2
          git push origin test2
      - name: Test action
        uses: ./
        with:
          branches: test1,test2