name: Test action

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Delete no branches
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: ''
          numbers: ''
          prefix: prefix
          suffix: suffix
