on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      BRANCH: test
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Ensure that branch does not exist
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: $BRANCH
          be_kind: true
      - name: Create branch
        uses: peterjgrainger/action-create-branch@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: $BRANCH
      - name: Delete branch
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: $BRANCH
